site_name: 敏捷攀樹手冊
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  extra:
    homepage: https://agile-tree-climbing-manual.readthedocs.io
  language: zh-TW
  nav_style: dark
  highlightjs: true
  hljs_languages:
    - yaml
    - rust
  palette:
    - scheme: default
      toggle:
        name: Switch to dark mode
        icon: material/toggle-switch
      primary: blue
    - scheme: slate
      toggle:
        name: Switch to light mode
        icon: material/toggle-switch-off-outline
      primary: indigo
  features:
    # - navigation.instant # 當點擊其他頁面時網頁不會重新整理且表留只在首頁
    - navigation.tracking
    # - navigation.tabs # 目錄橫放至頂端
    # - navigation.tabs.sticky # 目錄橫放至頂端
    # - navigation.sections # 左側目錄全部攤開
    - navigation.expand # 左側目錄全部攤開但可以收合
    - navigation.top
    # - toc.integrate # 右側目錄加入至左側目錄
    - search.suggest # 建議搜尋功能
    # - navigation.indexes # 只顯示部份索引
    - search.highlight
    - search.share
repo_url: https://github.com/Uesugi-Summer-Sea/Agile-Tree-Climbing-Manual
plugins:
  - search
  - mermaid2
authors: Chenzhi Wu
nav:
  - 序章: 'README.md'
  - 第1章 理念與目標:
    - 簡介: 01-理念與目標/README.md
    - 第1節 創意學習: 01-理念與目標/1-創意學習.md
  - 第2章 安全守則與規範:
    - 簡介: 02-安全守則與規範/README.md
    - 第1節 綜合性風險評估: 02-安全守則與規範/1-綜合性風險評估.md
    - 第2節 環境風險評估: 02-安全守則與規範/2-環境風險評估.md
    - 第3節 樹木風險評估: 02-安全守則與規範/3-樹木風險評估.md
    - 第4節 器械使用規範: 02-安全守則與規範/4-器械使用規範.md
    - 第5節 繩結使用規範: 02-安全守則與規範/5-繩結使用規範.md
    - 第6節 攀樹安全守則: 02-安全守則與規範/6-攀樹安全守則.md
    - 第7節 無痕山林: 02-安全守則與規範/7-無痕山林.md
  - 第3章 攀樹技術:
    - 簡介: 03-攀樹技術/README.md
    - 第1節 攀樹裝備: 03-攀樹技術/1-攀樹裝備.md
    - 第2節 繩結技術: 03-攀樹技術/2-繩結技術.md
    - 第3節 模組化: 03-攀樹技術/3-模組化.md
    - 第4節 攀樹系統: 03-攀樹技術/4-攀樹系統.md
    - 第5節 攀樹技巧: 03-攀樹技術/5-攀樹技巧.md
  - 第 4 章 跨領域應用與永續經營:
    - 簡介: 04-跨領域應用與永續經營/README.md
  - 第 5 章 樹木管理: 
    - 簡介: 05-樹木管理/README.md
    - 第 1 節 報名表範例: 05-樹木管理/3-報名表範例.md
    - 第 2 節 人工造林: 05-樹木管理/5-人工造林.md
    - 第 3 節 規劃與執行: 05-樹木管理/5-規劃與執行.md
    - 第 4 節 證照: 05-樹木管理/6-證照.md
  - 第 6 章 樹木工程: 
    - 簡介: 06-樹木工程/README.md
  - 第 7 章 樹藝與樹醫: 
    - 簡介: 07-樹藝與樹醫/README.md
    - 第 1 節 樹木生理結構: 07-樹藝與樹醫/1-樹木生理結構.md
    - 第 2 節 樹藝: 07-樹藝與樹醫/2-樹藝.md
    - 第 3 節 樹木常見病蟲害: 07-樹藝與樹醫/3-樹木常見病蟲害.md
    - 第 4 節 樹醫: 07-樹藝與樹醫/4-樹醫.md
  - 第 7 章 學術與教育: 
    - 簡介: 08-學術與教育/README.md
    - 第 1 節 休閒活動: 08-學術與教育/1-休閒活動.md
    - 第 2 節 國小社團活動課程: 08-學術與教育/1-國小社團活動課程.md
    - 第 3 節 教練與助教培訓課程: 08-學術與教育/2-教練與助教培訓課程.md
    - 第 4 節 運動競賽: 08-學術與教育/2-運動競賽.md
    - 第 5 節 社會工作: 08-學術與教育/3-社會工作.md
    - 第 6 節 教育: 08-學術與教育/4-教育.md
    - 第 7 節 生態調查: 08-學術與教育/4-生態調查.md
  - 第 8 章 學術與教育: 
    - 簡介: 08-學術與教育/README.md
    - 第 1 節 社群參與: 09-社群與專案/1-社群參與.md
    - 第 2 節 核心成員: 09-社群與專案/2-核心成員.md
  - 第 9 章 社群與專案: 
    - 簡介: 09-社群與專案/README.md
  - 第 10 章社群與專案:
    - 第 1 節 參考資料: 10-附錄/1-參考資料.md
    - 第 2 節 索引: 10-附錄/2-索引.md
    - 第 3 節 附錄: 10-附錄/2-附錄.md
    - 第 4 節 問卷調查: 10-附錄/3-問卷調查.md
    - 第 5 節 客戶滿意度調查問卷: 10-附錄/3-客戶滿意度調查問卷.md
  - 出版資訊: 出版資訊.md
markdown_extensions:
  - meta
  - smarty
  - mdx_truly_sane_lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.arithmatex:
      generic: true
  - markdown_katex:
      no_inline_svg: True
      insert_fonts_css: True
      macro-file: macros.tex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    property: UA-156555093-1
